In [2]:
# import libraries
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
# import bridge data
df_bridges = pd.read_csv('../data/bridges_cleaned.csv')
# drop old column named index
df_bridges = df_bridges.drop(["index", "Unnamed: 0"], axis='columns')
# add intersection to column
df_bridges['intersec_to'] = None
# reposition columns
df_bridges = df_bridges[['road', 'km', 'type', 'model_type', 'name', 'length', 'condition', 'lat', 'lon', 'intersec_to']]

In [4]:
df_bridges

,road,km,type,model_type,name,length,condition,lat,lon,intersec_to
0,N1,0.000,sourcesink,sourcesink,source,0.00,NaN,23.706028,90.443333,None
1,N1,1.800,Box Culvert,bridge,.,11.30,A,23.698739,90.458861,None
2,N1,4.925,Box Culvert,bridge,.,6.60,A,23.694664,90.487775,None
3,N1,8.976,PC Girder Bridge,bridge,KANCHPUR PC GIRDER BRIDGE,397.00,C,23.705060,90.523214,None
4,N1,10.543,Box Culvert,bridge,KATCHPUR BOX CULVERT,8.00,B,23.696400,90.535099,None
...,...,...,...,...,...,...,...,...,...,...
19212,Z8943,6.692,Truss with Steel Deck,bridge,.,31.07,A,22.428621,90.788543,None
19213,Z8943,6.767,Box Culvert,bridge,.,1.93,A,22.428872,90.787904,None
19214,Z8943,8.104,RCC Girder Bridge,bridge,.,12.00,C,22.430219,90.775203,None
19215,Z8943,8.609,Truss with Steel Deck,bridge,.,31.07,A,22.428889,90.788333,None
19216,Z8943,8.800,sourcesink,sourcesink,sink,0.00,NaN,22.430166,90.768916,None

In [6]:
# import intersections data
df_intersections = pd.read_csv('../data/intersections_main.csv')
# change chainage into km
df_intersections.rename({'chainage': 'km'}, axis=1, inplace=True)
# create model_type
df_intersections['model_type'] = 'intersection'
# create length
df_intersections['length'] = 0
# align intersection columns with bridge colum
# create condition
df_intersections['condition'] = None
# format colum,ns
df_intersections = df_intersections[['road', 'km', 'type', 'model_type', 'name', 'length', 'condition', 'lat', 'lon', 'intersec_to']]

In [7]:
df_intersections

,road,km,type,model_type,name,length,condition,lat,lon,intersec_to
0,N1,8.763,intersection,intersection,Road to Sylhet (N2),0,None,23.706083,90.521527,N102
1,N1,81.846,intersection,intersection,Road to Brahmanbaria(N102),0,None,23.478972,91.118166,N104
2,N1,100.071,intersection,intersection,Bridge start,0,None,23.377972,91.240361,N112
3,N1,143.946,intersection,intersection,Box culvert,0,None,23.018527,91.370833,N120
4,N1,145.409,intersection,intersection,Intersection with N104 / Km post missing,0,None,23.009556,91.381360,N129
5,N1,215.896,intersection,intersection,Km post missing,0,None,22.502556,91.713056,N2
6,N2,0.000,intersection,intersection,Road Start from N1 at Katchpur,0,None,23.705917,90.521444,N1
7,N2,11.476,intersection,intersection,Bridge start,0,None,23.785389,90.568888,N105
8,N2,71.638,intersection,intersection,Box Culvert,0,None,24.050833,90.990111,N203
9,N2,227.756,intersection,intersection,N209 / N208 to Moulovibazar,0,None,24.877694,91.875277,N209

In [ ]:
###
###
###

###
### Modify bridge data
###

# import bridge data
df_bridges = pd.read_csv('../data/bridges_cleaned.csv')
# drop old column named index
df_bridges = df_bridges.drop(["index", "Unnamed: 0"], axis='columns')
# add intersection to column
df_bridges['intersec_to'] = None
# reposition columns
df_bridges = df_bridges[['road', 'km', 'type', 'model_type', 'name', 'length', 'condition', 'lat', 'lon', 'intersec_to']]

###
### Modify intersection data, align with bridge data
###

# import intersections data
df_intersections = pd.read_csv('../data/intersections_main.csv')
# change chainage into km
df_intersections.rename({'chainage': 'km'}, axis=1, inplace=True)
# create model_type
df_intersections['model_type'] = 'intersection'
# create length
df_intersections['length'] = 0
# align intersection columns with bridge colum
# create condition
df_intersections['condition'] = None
# format colum,ns
df_intersections = df_intersections[['road', 'km', 'type', 'model_type', 'name', 'length', 'condition', 'lat', 'lon', 'intersec_to']]

###
### Check if intersected road is longer than 25 km
###

# get all intersected roads
intersections = df_intersections['intersec_to'].unique().tolist()
# remove nan if present
intersections = [x for x in intersections if str(x) != 'nan']
# for each road which is an intersection of N1 or N2
for intersection in intersections: 
    # subset all data points for the road
    road_subset = df_bridges[df_bridges['road'] == intersection]
    # get last chainage
    road_length = road_subset.iloc[-1]['km']
    if road_length < 25: 
        intersections.remove(intersection)
# remove left-overs by hand
intersections.remove('N120')
intersections.remove('N209')

###
### Merge bridges with intersection points
###

# keep all bridges in roads that intersect
df_bridges = df_bridges[df_bridges['road'].isin(intersections)]
# keep all roads which are still in intersections list, so longer than 25 km
df_intersections = df_intersections[df_intersections['intersec_to'].isin(intersections)] 
# get the dataframes which needs to be merged
frames = [df_bridges, df_intersections]
# merge dataframes into df
df = pd.concat(frames)

###
### Format data
###

# sort roads dataframe based on road name and chainage
df = df.sort_values(by=['road', 'km'])
# reset index
df = df.reset_index(drop=True) 
# get index to remove, which is a duplicate for N2 
index_to_remove = df[(df['road'] == 'N2') & (df['km'] == 0.0) & (df['model_type'] == 'sourcesink')].index
# drop index
df = df.drop(df[(df['road'] == 'N2') & (df['km'] == 0.0) & (df['model_type'] == 'sourcesink')].index)

# save merged dataframe as CSV file
df.to_csv('../data/bridges_cleaned_intersected_long.csv')