In [1]:
import pandas as pd

In [2]:
df_scenario0 = pd.read_csv('experiment/scenario0.csv')
df_scenario1 = pd.read_csv('experiment/scenario1.csv')
dfs = []

In [ ]:
def adding_scenario_column(df, s):
    # Add a column with the number of the scenario
    df['scenario'] = s
    return df

In [ ]:
def create_subset(df):
    # Create a subset of the dataframe with the desired columns
    df_subset = df[['scenario', 'iteration', 'Step', 
                    'avg_delay', 'avg_waiting','avg_driving_time', 'avg_speed',
                    'tot_collapsed', 'A_collapsed', 'B_collapsed', 'C_collapsed', 'D_collapsed']]
    return df_subset

In [ ]:
def concat_dfs(dfs):
    # Create an empty list to store the cleaned dataframes in
    df_list = []
    # Loop over the dataframes
    for s, df in enumerate(dfs):
        # Add a column with the scenario number
        df = adding_scenario_column(df, s)
        # Create a subset of the dataframe
        df_subset = create_subset(df)
        # Append the cleaned dataframe to the list
        df_list.append(df_subset)
    # Concat the dataframes in the list
    full_df = pd.concat(df_list, ignore_index=True)
    return full_df

In [4]:
df_s0 = df_scenario0[['iteration', 'Step', 'avg_delay', 'avg_waiting', 'avg_driving_time', 'avg_speed', 'tot_collapsed', 'A_collapsed', 'B_collapsed', 'C_collapsed', 'D_collapsed']]
df_s0

,iteration,Step,avg_delay,avg_waiting,avg_driving_time,avg_speed,tot_collapsed,A_collapsed,B_collapsed,C_collapsed,D_collapsed
0,0,0,0,0,0.000000,0.000000,0,0,0,0,0
1,0,1,0,0,0.000000,0.000000,0,0,0,0,0
2,0,2,0,0,0.000000,0.000000,0,0,0,0,0
3,0,3,0,0,0.000000,0.000000,0,0,0,0,0
4,0,4,0,0,0.000000,0.000000,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
72005,9,7196,0,0,257.222645,47.701090,0,0,0,0,0
72006,9,7197,0,0,257.222645,47.701090,0,0,0,0,0
72007,9,7198,0,0,257.225433,47.701097,0,0,0,0,0
72008,9,7199,0,0,257.215276,47.701106,0,0,0,0,0
72009,9,7200,0,0,257.244221,47.701235,0,0,0,0,0